{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "c8e7f4b7_a4fa9693",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 8667
      },
      "writtenOn": "2022-06-17T09:33:43Z",
      "side": 1,
      "message": "There seems to be an issue with the tapi tests, when it fails on one test it restarts performing all the tests again (see log obtained locally), hence the timeout error:\n.....................F.....................F\n^C\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_22_delete_connectivity_service_DSR (test02_full_topology.TransportPCEtesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/Users/erreamor/transportpce/tests/transportpce_tests/tapi/test02_full_topology.py\", line 454, in test_22_delete_connectivity_service_DSR\n    self.assertEqual(response.status_code, requests.codes.no_content)\nAssertionError: 500 !\u003d 204\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\n{\"input\": {\"service-id-or-name\": \"0f30c62e-94f4-4d8d-bb13-12f521f98fe9\"}}\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8181\nurllib3.connectionpool: DEBUG: http://localhost:8181 \"POST /restconf/operations/tapi-connectivity:delete-connectivity-service HTTP/1.1\" 500 182\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n----------------------------------------------------------------------\nRan 23 tests in 1410.864s\n\nAlso when connecting the nodes to the controller the response code was 200 and not 201. Therefore I modified assertEquals by assertIn. I dont know if this is a behavior on my OS or overall...",
      "revId": "1828c683feb775065b043f02b685e5084f9fbbe5",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "eaad4b5e_4b0b27b0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 8667
      },
      "writtenOn": "2022-06-17T09:34:15Z",
      "side": 1,
      "message": "@Gilles @Guillaume",
      "parentUuid": "c8e7f4b7_a4fa9693",
      "revId": "1828c683feb775065b043f02b685e5084f9fbbe5",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "7c26503f_7dfa3aad",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 7446
      },
      "writtenOn": "2022-06-20T07:55:26Z",
      "side": 1,
      "message": "Hi Javier,\nIt must have a bug in the connection deletion. It seems that the deletion of the DSR service fails, and TransportPCE seems entering in a kind of infinite loop to find the connection to delete, without any success.\nBut, since there is no check in the test_22 to wait deletion process is correctly done, it directly passes to test_23 before TransportPCE ends its failure, and blocks immediatly in that latter. After that, nothing new happens and I suppose this is maybe nosetest or tox timeout that tries to relaunch once the test suite.",
      "parentUuid": "eaad4b5e_4b0b27b0",
      "revId": "1828c683feb775065b043f02b685e5084f9fbbe5",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "e4878c7c_e6473665",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 6731
      },
      "writtenOn": "2022-06-20T08:11:16Z",
      "side": 1,
      "message": "good point Javier. Maybe an exit well placed in the python script in case of failure can solve this issue.",
      "parentUuid": "7c26503f_7dfa3aad",
      "revId": "1828c683feb775065b043f02b685e5084f9fbbe5",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "73f9746c_4c51b344",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 9
      },
      "lineNbr": 0,
      "author": {
        "id": 8667
      },
      "writtenOn": "2022-06-27T15:59:43Z",
      "side": 1,
      "message": "I think I have fix it. Lets see if it will pass the gate or not",
      "parentUuid": "e4878c7c_e6473665",
      "revId": "1828c683feb775065b043f02b685e5084f9fbbe5",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "730cd791_b6b7b945",
        "filename": "tests/transportpce_tests/tapi/test02_full_topology.py",
        "patchSetId": 9
      },
      "lineNbr": 160,
      "author": {
        "id": 6731
      },
      "writtenOn": "2022-06-20T08:11:16Z",
      "side": 1,
      "message": "LGTM\nthere are a bunch of tests that must support both 200 and 201 return codes.\nPlease can you propose a separate change for this at the bottom of the stack ?\nWe need to repercute this modification where needed.",
      "revId": "1828c683feb775065b043f02b685e5084f9fbbe5",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "551c00be_d584a7c6",
        "filename": "tests/transportpce_tests/tapi/test02_full_topology.py",
        "patchSetId": 9
      },
      "lineNbr": 160,
      "author": {
        "id": 7446
      },
      "writtenOn": "2022-06-20T08:17:40Z",
      "side": 1,
      "message": "The normal return code must be 200. Adding 201 here is a bad work-around. 201 is probably due to the fact that the test suite restarts after not being completely correctly finished, and with an initial state where devices have not been correctly disconnected from the controller.",
      "parentUuid": "730cd791_b6b7b945",
      "revId": "1828c683feb775065b043f02b685e5084f9fbbe5",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "c24c7b58_55562f29",
        "filename": "tests/transportpce_tests/tapi/test02_full_topology.py",
        "patchSetId": 9
      },
      "lineNbr": 160,
      "author": {
        "id": 6731
      },
      "writtenOn": "2022-06-20T09:06:26Z",
      "side": 1,
      "message": "fair enough but in that case, I think we must modify the mount_tapi_device() function that lets think that this is not the normal behavior and that is not very efficient in that case. cf below\nWe must also consider the move towards RFC8040. It modified some return codes.\n\n    if wait_until_log_contains(TPCE_LOG, re.escape(f\"TAPI node for or node {node_id} successfully merged\"), 200):\n        print(\"Node \" + node_id + \" correctly added to tpce topology\", end\u003d\u0027... \u0027, flush\u003dTrue)\n    else:\n        print(\"Node \" + node_id + \" still not added to tpce topology\", end\u003d\u0027... \u0027, flush\u003dTrue)\n        if response.status_code \u003d\u003d requests.codes.ok:\n            print(\"It was probably loaded at start-up\", end\u003d\u0027... \u0027, flush\u003dTrue)\n        # TODO an else-clause to abort test would probably be nice here\n    return response",
      "parentUuid": "551c00be_d584a7c6",
      "revId": "1828c683feb775065b043f02b685e5084f9fbbe5",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "c2bcea4a_df425aa4",
        "filename": "tests/transportpce_tests/tapi/test02_full_topology.py",
        "patchSetId": 9
      },
      "lineNbr": 160,
      "author": {
        "id": 8667
      },
      "writtenOn": "2022-06-27T15:59:43Z",
      "side": 1,
      "message": "I have removed it for now. But I will create a separate change addressing this. Maybe we can discuss it next Thursday",
      "parentUuid": "c24c7b58_55562f29",
      "revId": "1828c683feb775065b043f02b685e5084f9fbbe5",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    }
  ]
}