{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "cf6001a2_05658529",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 6731
      },
      "writtenOn": "2022-08-27T13:54:44Z",
      "side": 1,
      "message": "python3 -m pytest -q transportpce_tests/hybrid/test03_autonomous_reroute.py\n................................F....F..........                                                                                                                                                                                       [100%]\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d FAILURES \u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\n___________________________________________________________________________________________ TransportPCEtesting.test_33_get_service_path_service_1 ___________________________________________________________________________________________\n\nself \u003d \u003chybrid.test03_autonomous_reroute.TransportPCEtesting testMethod\u003dtest_33_get_service_path_service_1\u003e\n\n    def test_33_get_service_path_service_1(self):\n        response \u003d test_utils_rfc8040.get_serv_path_list_attr(\"service-paths\", \"service1\")\n        self.assertEqual(response[\u0027status_code\u0027], requests.codes.ok)\n\u003e       self.assertCountEqual(\n            self.service_path_service_1_AtoZ,\n            response[\u0027service-paths\u0027][0][\u0027path-description\u0027][\u0027aToZ-direction\u0027][\u0027aToZ\u0027])\nE       AssertionError: Element counts were not equal:\nE       \nE       Diff is 5201 characters long. Set self.maxDiff to None to see it.\n\ntransportpce_tests/hybrid/test03_autonomous_reroute.py:1078: AssertionError\n___________________________________________________________________________________________ TransportPCEtesting.test_38_get_service_path_service_1 ___________________________________________________________________________________________\n\nself \u003d \u003chybrid.test03_autonomous_reroute.TransportPCEtesting testMethod\u003dtest_38_get_service_path_service_1\u003e\n\n    def test_38_get_service_path_service_1(self):\n\u003e       self.test_33_get_service_path_service_1()\n\ntransportpce_tests/hybrid/test03_autonomous_reroute.py:1156: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntransportpce_tests/hybrid/test03_autonomous_reroute.py:1078: in test_33_get_service_path_service_1\n    self.assertCountEqual(\nE   AssertionError: Element counts were not equal:\nE   \nE   Diff is 5201 characters long. Set self.maxDiff to None to see it.\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d short test summary info \u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAILED transportpce_tests/hybrid/test03_autonomous_reroute.py::TransportPCEtesting::test_33_get_service_path_service_1 - AssertionError: Element counts were not equal:\nFAILED transportpce_tests/hybrid/test03_autonomous_reroute.py::TransportPCEtesting::test_38_get_service_path_service_1 - AssertionError: Element counts were not equal:\n2 failed, 46 passed in 286.88s (0:04:46)\nERROR: InvocationError for command /home/guillaume/git_ws/transportpce/tests/launch_tests.sh hybrid autonomous_reroute (exited with code 1)\n__________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________\nERROR:   tests_hybrid: commands failed\n",
      "revId": "6073d0f5a9115519def13dca850b99cc929c8a3e",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    }
  ]
}