{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "00c8f59c_5c5108d8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 6731
      },
      "writtenOn": "2021-11-24T15:36:58Z",
      "side": 1,
      "message": "pylint not available in nexus odl\n\n15:56:51 Collecting pylint\n15:56:51   ERROR: HTTP error 502 while getting https://nexus3.opendaylight.org/repository/PyPi/packages/pylint/2.11.1/pylint-2.11.1-py3-none-any.whl#sha256\u003d0f358e221c45cbd4dad2a1e4b883e75d28acdcccd29d40c76eb72b307269b126 (from https://nexus3.opendaylight.org/repository/PyPi/simple/pylint/) (requires-python:~\u003d3.6)\n15:56:51 ERROR: Could not install requirement pylint from https://nexus3.opendaylight.org/repository/PyPi/packages/pylint/2.11.1/pylint-2.11.1-py3-none-any.whl#sha256\u003d0f358e221c45cbd4dad2a1e4b883e75d28acdcccd29d40c76eb72b307269b126 because of HTTP error 502 Server Error: Bad Gateway for url: https://nexus3.opendaylight.org/repository/PyPi/packages/pylint/2.11.1/pylint-2.11.1-py3-none-any.whl for URL https://nexus3.opendaylight.org/repository/PyPi/packages/pylint/2.11.1/pylint-2.11.1-py3-none-any.whl#sha256\u003d0f358e221c45cbd4dad2a1e4b883e75d28acdcccd29d40c76eb72b307269b126 (from https://nexus3.opendaylight.org/repository/PyPi/simple/pylint/) (requires-python:~\u003d3.6)\n15:56:51 \n15:56:51 \u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d log end \u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\n15:56:51 ERROR: could not install deps [pylint]; v \u003d InvocationError(\u0027/w/workspace/transportpce-tox-verify-sulfur/.tox/pylint/bin/python -m pip install pylint\u0027, 1)\n15:56:51 ERROR: invocation failed (exit code 1)\n15:56:51 âœ– FAIL pylint in 3.882 seconds",
      "revId": "6a31109f21e577024c0e89728cf877d32174fe88",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    }
  ]
}