{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "cba0ae45_67d59acb",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 6731
      },
      "writtenOn": "2022-01-29T22:15:00Z",
      "side": 1,
      "message": "Got a HTTP code 503 (service unavailable) instead of 409 (conflict) with RFC8040 URL\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_23_check_no_interface_otuc2 (test02_otn_renderer.TransportPCE400GPortMappingTesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/w/workspace/transportpce-tox-verify-sulfur/tests/transportpce_tests/7.1/test02_otn_renderer.py\", line 405, in test_23_check_no_interface_otuc2\n    self.assertEqual(response[\u0027status_code\u0027], requests.codes.conflict)\nAssertionError: 503 !\u003d 409\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\nexecution of test_23_check_no_interface_otuc2\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8184\nurllib3.connectionpool: DEBUG: http://localhost:8184 \"GET /rests/data/network-topology:network-topology/topology\u003dtopology-netconf/node\u003dXPDR-A1/yang-ext:mount/org-openroadm-device:org-openroadm-device/interface\u003dXPDR2-NETWORK1-OTUC2?content\u003dnonconfig HTTP/1.1\" 503 197\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_24_check_no_interface_otsig (test02_otn_renderer.TransportPCE400GPortMappingTesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/w/workspace/transportpce-tox-verify-sulfur/tests/transportpce_tests/7.1/test02_otn_renderer.py\", line 410, in test_24_check_no_interface_otsig\n    self.assertEqual(response[\u0027status_code\u0027], requests.codes.conflict)\nAssertionError: 503 !\u003d 409\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\nexecution of test_24_check_no_interface_otsig\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8184\nurllib3.connectionpool: DEBUG: http://localhost:8184 \"GET /rests/data/network-topology:network-topology/topology\u003dtopology-netconf/node\u003dXPDR-A1/yang-ext:mount/org-openroadm-device:org-openroadm-device/interface\u003dXPDR2-NETWORK1-OTSIGROUP-200G?content\u003dnonconfig HTTP/1.1\" 503 197\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_25_check_no_interface_otsi (test02_otn_renderer.TransportPCE400GPortMappingTesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/w/workspace/transportpce-tox-verify-sulfur/tests/transportpce_tests/7.1/test02_otn_renderer.py\", line 414, in test_25_check_no_interface_otsi\n    self.assertEqual(response[\u0027status_code\u0027], requests.codes.conflict)\nAssertionError: 503 !\u003d 409\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\nexecution of test_25_check_no_interface_otsi\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8184\nurllib3.connectionpool: DEBUG: http://localhost:8184 \"GET /rests/data/network-topology:network-topology/topology\u003dtopology-netconf/node\u003dXPDR-A1/yang-ext:mount/org-openroadm-device:org-openroadm-device/interface\u003dXPDR2-NETWORK1-755:768?content\u003dnonconfig HTTP/1.1\" 503 197\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_37_check_no_interface_otuc3 (test02_otn_renderer.TransportPCE400GPortMappingTesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/w/workspace/transportpce-tox-verify-sulfur/tests/transportpce_tests/7.1/test02_otn_renderer.py\", line 611, in test_37_check_no_interface_otuc3\n    self.assertEqual(response[\u0027status_code\u0027], requests.codes.conflict)\nAssertionError: 503 !\u003d 409\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\nexecution of test_37_check_no_interface_otuc3\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8184\nurllib3.connectionpool: DEBUG: http://localhost:8184 \"GET /rests/data/network-topology:network-topology/topology\u003dtopology-netconf/node\u003dXPDR-A1/yang-ext:mount/org-openroadm-device:org-openroadm-device/interface\u003dXPDR2-NETWORK1-OTUC3?content\u003dnonconfig HTTP/1.1\" 503 197\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_38_check_no_interface_otsig (test02_otn_renderer.TransportPCE400GPortMappingTesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/w/workspace/transportpce-tox-verify-sulfur/tests/transportpce_tests/7.1/test02_otn_renderer.py\", line 616, in test_38_check_no_interface_otsig\n    self.assertEqual(response[\u0027status_code\u0027], requests.codes.conflict)\nAssertionError: 503 !\u003d 409\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\nexecution of test_38_check_no_interface_otsig\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8184\nurllib3.connectionpool: DEBUG: http://localhost:8184 \"GET /rests/data/network-topology:network-topology/topology\u003dtopology-netconf/node\u003dXPDR-A1/yang-ext:mount/org-openroadm-device:org-openroadm-device/interface\u003dXPDR2-NETWORK1-OTSIGROUP-300G?content\u003dnonconfig HTTP/1.1\" 503 197\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_39_check_no_interface_otsi (test02_otn_renderer.TransportPCE400GPortMappingTesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/w/workspace/transportpce-tox-verify-sulfur/tests/transportpce_tests/7.1/test02_otn_renderer.py\", line 620, in test_39_check_no_interface_otsi\n    self.assertEqual(response[\u0027status_code\u0027], requests.codes.conflict)\nAssertionError: 503 !\u003d 409\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\nexecution of test_39_check_no_interface_otsi\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8184\nurllib3.connectionpool: DEBUG: http://localhost:8184 \"GET /rests/data/network-topology:network-topology/topology\u003dtopology-netconf/node\u003dXPDR-A1/yang-ext:mount/org-openroadm-device:org-openroadm-device/interface\u003dXPDR2-NETWORK1-755:768?content\u003dnonconfig HTTP/1.1\" 503 197\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_51_check_no_interface_otuc4 (test02_otn_renderer.TransportPCE400GPortMappingTesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/w/workspace/transportpce-tox-verify-sulfur/tests/transportpce_tests/7.1/test02_otn_renderer.py\", line 817, in test_51_check_no_interface_otuc4\n    self.assertEqual(response[\u0027status_code\u0027], requests.codes.conflict)\nAssertionError: 503 !\u003d 409\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\nexecution of test_51_check_no_interface_otuc4\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8184\nurllib3.connectionpool: DEBUG: http://localhost:8184 \"GET /rests/data/network-topology:network-topology/topology\u003dtopology-netconf/node\u003dXPDR-A1/yang-ext:mount/org-openroadm-device:org-openroadm-device/interface\u003dXPDR2-NETWORK1-OTUC4?content\u003dnonconfig HTTP/1.1\" 503 197\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_52_check_no_interface_otsig (test02_otn_renderer.TransportPCE400GPortMappingTesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/w/workspace/transportpce-tox-verify-sulfur/tests/transportpce_tests/7.1/test02_otn_renderer.py\", line 822, in test_52_check_no_interface_otsig\n    self.assertEqual(response[\u0027status_code\u0027], requests.codes.conflict)\nAssertionError: 503 !\u003d 409\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\nexecution of test_52_check_no_interface_otsig\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8184\nurllib3.connectionpool: DEBUG: http://localhost:8184 \"GET /rests/data/network-topology:network-topology/topology\u003dtopology-netconf/node\u003dXPDR-A1/yang-ext:mount/org-openroadm-device:org-openroadm-device/interface\u003dXPDR2-NETWORK1-OTSIGROUP-400G?content\u003dnonconfig HTTP/1.1\" 503 197\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_53_check_no_interface_otsi (test02_otn_renderer.TransportPCE400GPortMappingTesting)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/w/workspace/transportpce-tox-verify-sulfur/tests/transportpce_tests/7.1/test02_otn_renderer.py\", line 826, in test_53_check_no_interface_otsi\n    self.assertEqual(response[\u0027status_code\u0027], requests.codes.conflict)\nAssertionError: 503 !\u003d 409\n-------------------- \u003e\u003e begin captured stdout \u003c\u003c ---------------------\nexecution of test_53_check_no_interface_otsi\n\n--------------------- \u003e\u003e end captured stdout \u003c\u003c ----------------------\n-------------------- \u003e\u003e begin captured logging \u003c\u003c --------------------\nurllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:8184\nurllib3.connectionpool: DEBUG: http://localhost:8184 \"GET /rests/data/network-topology:network-topology/topology\u003dtopology-netconf/node\u003dXPDR-A1/yang-ext:mount/org-openroadm-device:org-openroadm-device/interface\u003dXPDR2-NETWORK1-755:768?content\u003dnonconfig HTTP/1.1\" 503 197\n--------------------- \u003e\u003e end captured logging \u003c\u003c ---------------------\n\n----------------------------------------------------------------------\nRan 56 tests in 623.116s\n\nFAILED (failures\u003d9)\nERROR: InvocationError for command /w/workspace/transportpce-tox-verify-sulfur/tests/launch_tests.sh 7.1 (exited with code 1)\nERROR: invocation failed (exit code 1)\n✖ FAIL tests71 in 13 minutes, 33.153 seconds",
      "revId": "785e24d1f5c2fd8cc8e8f8219c55e836ebbc5f89",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    }
  ]
}